---
- name: Register Linux Proxy in Veeam Backup for Microsoft 365
  hosts: all
  gather_facts: no
  become: no

  # vars:
  #   vb365_hostname: "{{ vb365_hostname }}"
  #   vb365_username: "{{ vb365_username }}"
  #   vb365_password: "{{ vb365_password }}"
  #   proxy_fqdn: "{{ proxy_fqdn }}"
  #   proxy_username: "{{ proxy_username }}"
  #   proxy_password: "{{ proxy_password }}"
  #   proxy_port: "{{ proxy_port | default(22) }}"

  tasks:

  - name: Tilføj Linux Proxy i Veeam Backup for Microsoft 365
    ansible.windows.win_powershell:
          script: |

            Import-Module Veeam.Archiver.PowerShell


            $vbHost = "{{ vb365_hostname }}"
            $vbUser = "{{ vb365_username }}"
            $vbPass = ConvertTo-SecureString "{{ vb365_password }}" -AsPlainText -Force
            $vbCred = New-Object System.Management.Automation.PSCredential($vbUser, $vbPass)


            Connect-VBOServer -Server $vbHost -Credential $vbCred -ErrorAction Stop


            $proxyHostname = "{{ proxy_fqdn }}"
            $pUser = "{{ proxy_username }}"
            $pPass = ConvertTo-SecureString "{{ proxy_password }}" -AsPlainText -Force
            $pCred = New-Object System.Management.Automation.PSCredential($pUser, $pPass)


            $LinuxCred = New-VBOLinuxCredential -Credentials $pCred

            $existing = Get-VBOProxy | Where-Object { $_.Hostname -eq $proxyHostname }

            if (!$existing) {

                Add-VBOProxy `
                  -Hostname $proxyHostname ` 
                  -LinuxCredential $LinuxCred `
                  -Port {{ proxy_port }}
                
                Write-Host "Proxy $proxyHostname er tilføjet."
            } else {
                Write-Host "Proxy $proxyHostname eksisterer allerede."
            }
            register: add_proxy_result}