---
- name: Register Linux Proxy in Veeam Backup for Microsoft 365
  hosts: all
  gather_facts: no
  become: no

  # ... (Dine vars er kommenteret ud) ...

  tasks:

    - name: Tilføj Linux Proxy i Veeam Backup for Microsoft 365
      ansible.windows.win_powershell:
        script: |
          Import-Module Veeam.Archiver.PowerShell

          # 1. VBO Server Legitimationsoplysninger
          $vbHost = "{{ vb365_hostname }}"
          $vbUser = "{{ vb365_username }}"
          $vbPass = ConvertTo-SecureString "{{ vb365_password }}" -AsPlainText -Force
          $vbCred = New-Object System.Management.Automation.PSCredential($vbUser, $vbPass)

          # 2. Opret forbindelse til VBO Server (Stopper ved fejl)
          Connect-VBOServer -Server $vbHost -Credential $vbCred -ErrorAction Stop

          # 3. Definer variabler og SecureString for Linux Proxy
          $proxyHostname = "{{ proxy_fqdn }}"
          $pUser = "{{ proxy_username }}"
          $pPass = ConvertTo-SecureString "{{ proxy_password }}" -AsPlainText -Force

          # 4. Opret VBOLinuxCredential-objekt (Korrekt V8 Syntaks)
          $LinuxCred = New-VBOLinuxCredential `
            -Name "Ansible-{{ proxy_fqdn }}" ` 
            -UserName $pUser `
            -Password $pPass

          # 5. Tjek om Proxy allerede eksisterer
          $existing = Get-VBOProxy | Where-Object { $_.Hostname -eq $proxyHostname }

          if (!$existing) {

              # 6. Tilføj Proxy (Korrekt V8 Syntaks)
              Add-VBOProxy `
                -Hostname $proxyHostname ` 
                -LinuxCredential $LinuxCred `
                -Port {{ proxy_port }}
              
              Write-Host "Proxy $proxyHostname er tilføjet."
          } else {
              Write-Host "Proxy $proxyHostname eksisterer allerede."
          }
      register: add_proxy_result 