---
- name: Register Linux Proxy in Veeam Backup for Microsoft 365
  hosts: all
  gather_facts: no
  become: no

  # vars:
  #   vb365_hostname: "{{ vb365_hostname }}"
  #   vb365_username: "{{ vb365_username }}"
  #   vb365_password: "{{ vb365_password }}"
  #   proxy_fqdn: "{{ proxy_fqdn }}"
  #   proxy_username: "{{ proxy_username }}"
  #   proxy_password: "{{ proxy_password }}"
  #   proxy_port: "{{ proxy_port | default(22) }}"

  tasks:

    - name: Add Linux proxy to VB365
      ansible.windows.win_powershell:
        script: |
          Import-Module Veeam.Archiver.PowerShell

          $vbHost = "{{ vb365_hostname }}"
          $vbUser = "{{ vb365_username }}"
          $vbPass = ConvertTo-SecureString "{{ vb365_password }}" -AsPlainText -Force
          $vbCred = New-Object System.Management.Automation.PSCredential($vbUser, $vbPass)

          Connect-VBOServer -Server $vbHost -Credential $vbCred

          $proxyName = "{{ proxy_fqdn }}"
          $pUser = "{{ proxy_username }}"
          $pPass = ConvertTo-SecureString "{{ proxy_password }}" -AsPlainText -Force
          $pCred = New-Object System.Management.Automation.PSCredential($pUser, $pPass)

          $existing = Get-VBOLinuxProxy | Where-Object { $_.Name -eq $proxyName }
          if (!$existing) {
              Add-VBOLinuxProxy `
                -Name $proxyName `
                -Hostname $proxyName `
                -Credentials $pCred `
                -Port {{ proxy_port }}
              Write-Host "Proxy $proxyName added."
          } else {
              Write-Host "Proxy $proxyName already exists."
          }

