---
  - name: Register Linux Proxy in Veeam Backup for Microsoft 365
    hosts: controller   # <-- matcher inventory-gruppen ovenfor
    gather_facts: no
    become: no

    tasks:
      - name: Tilføj Linux Proxy i Veeam Backup for Microsoft 365
        ansible.windows.win_powershell:
          script: |
            Import-Module Veeam.Archiver.PowerShell

            $proxyHostname = "{{ proxy_fqdn }}"
            $pUser = "{{ proxy_username }}"
            $pPass = ConvertTo-SecureString -String "{{ proxy_password }}" -AsPlainText -Force
            $LinuxCred = New-VBOLinuxCredential -Account $pUser -ElevateAccountToRoot:$true -Password $pPass

            $existing = Get-VBOProxy | Where-Object { $_.Hostname -eq $proxyHostname }

            if (!$existing) {
                Add-VBOProxy -Hostname $proxyHostname -Port {{ proxy_port }} -LinuxCredential $LinuxCred -Force
                Write-Host "Proxy $proxyHostname er tilføjet."
            } else {
                Write-Host "Proxy $proxyHostname eksisterer allerede."
            }
        register: add_proxy_result

      - name: Vis resultat
        ansible.builtin.debug:
          var: add_proxy_result.output
    # - name: Install Graylog Sidecar RPM
    #   ansible.builtin.dnf:
    #     name: "{{ graylog_sidecar_rpm }}"
    #     state: present
    #     disable_gpg_check: true

    # - name: Configure Graylog Sidecar (sidecar.yml)
    #   ansible.builtin.template:
    #     src: templates/sidecar.yml.j2
    #     dest: "{{ sidecar_config }}"
    #     owner: root
    #     group: root
    #     mode: '0640'
    #   notify: Restart Graylog Sidecar

    # - name: Install Graylog Sidecar service
    #   ansible.builtin.command:
    #     cmd: graylog-sidecar -service install
    #     creates: /etc/systemd/system/graylog-sidecar.service

    # - name: Enable and start Graylog Sidecar
    #   ansible.builtin.systemd:
    #     name: graylog-sidecar
    #     enabled: true
    #     state: started
    #     daemon_reload: true

  # handlers:
  #   - name: Restart Graylog Sidecar
  #     ansible.builtin.systemd:
  #       name: graylog-sidecar
  #       state: restarted