---
- name: Promote server to secondary DC
  hosts: dc
  gather_facts: no

  tasks:
    - name: Ensure initial WinRM is reachable
      ansible.windows.win_wait_for:
        port: "{{ ansible_port }}"
        delay: 5
        timeout: 300
        host: "{{ ansible_host | default(inventory_hostname) }}"

    - name: Configure DNS to point to primary DC
      ansible.windows.win_shell: |
        $adapter = Get-NetAdapter | Where-Object { $_.Status -eq "Up" } | Select-Object -First 1
        if ($adapter) {
            # Peg på primær DC først, derefter denne server selv
            Set-DnsClientServerAddress -InterfaceAlias $adapter.Name -ServerAddresses ("{{ domain_controller }}", "127.0.0.1")
            Write-Host "DNS configured for $($adapter.Name)"
        }

    - name: Install AD DS feature
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present
      register: adds_install

    - name: Reboot if AD DS installation requires it
      ansible.windows.win_reboot:
        msg: "Rebooting after AD DS installation"
      when: adds_install.reboot_required

    - name: Promote to secondary domain controller
      microsoft.ad.domain_controller:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_user_password }}"
        safe_mode_password: "{{ recovery_password }}"
        install_dns: yes
        state: domain_controller
      register: dc_promotion

    - name: Reboot after DC promotion
      ansible.windows.win_reboot:
        msg: "Rebooting after DC promotion"
        post_reboot_delay: 60
      when: dc_promotion.reboot_required