- name: Domain Controller Setup - PART 2 (Promotion and Configuration)
  hosts: dc
  gather_facts: no

  tasks:
    - name: Wait for WinRM to be fully ready (with retries)
      ansible.windows.win_ping:
      retries: 30
      delay: 30
      register: result
      until: result is succeeded


    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path: C:\Windows\NTDS
        dns_domain_name: "{{ domain_name }}"
        domain_mode: WinThreshold
        domain_netbios_name: "{{ netbios }}"
        forest_mode: WinThreshold
        safe_mode_password: "{{ recovery_password }}"
        sysvol_path: C:\Windows\SYSVOL
        reboot: true
      register: domain_install

    - name: Create NATS server record
      ansible.windows.win_dns_record:
        name: "{{ nats_hostname }}"
        type: "A"
        value: "{{ nats_ip }}"
        zone: "{{ domain_name }}"

    - name: Create PGSQL server record
      ansible.windows.win_dns_record:
        name: "{{ postgres_hostname }}"
        type: "A"
        value: "{{ postgres_ip }}"
        zone: "{{ domain_name }}"

    - name: Wait for DNS service to be ready
      ansible.windows.win_service:
        name: DNS
        state: started
      register: dns_service
      retries: 10
      delay: 15
      until: dns_service is succeeded

    - name: Configure DNS forwarders
      ansible.windows.win_shell: |
        $desired = @("161.26.0.7","161.26.0.8")
        $current = (Get-DnsServerForwarder).IPAddress

        if (-not $current -or (@($current) -ne $desired)) {
            Set-DnsServerForwarder -IPAddress $desired -PassThru
        } else {
            Write-Output "Forwarders already correct"
        }
    - name: Verify DNS forwarders
      ansible.windows.win_shell: |
        Get-DnsServerForwarder | Select-Object IPAddress
      register: dns_forwarders

    - debug:
        var: dns_forwarders.stdout_lines
 