---
- name: Configure Domain Controller
  hosts: dc
  vars:
    dc_address: "{{ dc_address }}"
    dc_hostname: "{{ dc_hostname }}"
    domain_name: "{{ domain_name }}"
    dc_password: "{{ dc_password }}"
    recovery_password: "{{ recovery_password }}"
    upstream_dns_1: "{{ upstream_dns_1 }}"
    upstream_dns_2: "{{ upstream_dns_2 }}"
    ntp_servers: "{{ ntp_servers }}"
  gather_facts: no

  tasks:
    - name: Wait for WinRM to become available
      wait_for:
        host: "{{ dc_address }}"
        port: 5986
        timeout: 600       # vent op til 10 minutter
        state: started

    - name: Set administrator password
      win_user:
        name: Administrator
        password: "{{ dc_password }}"
        state: present

    - name: Set upstream DNS
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
          - "{{ upstream_dns_1 }}"
          - "{{ upstream_dns_2 }}"

    - name: Install Active Directory Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Create Domain
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ recovery_password }}"
      register: ad_domain

    - name: Reboot after AD install
      win_reboot:
        msg: "Rebooting after domain promotion"
        pre_reboot_delay: 15
      when: ad_domain.changed
