- name: Domain Controller Setup - PART 2 (Promotion and Configuration)
  hosts: dc
  gather_facts: no

  tasks:
    - name: Wait for WinRM to be fully ready (with retries)
      ansible.windows.win_ping:
      retries: 30
      delay: 30
      register: result
      until: result is succeeded


    - name: Create new Windows domain in a new forest with specific parameters and reboot in post task
      microsoft.ad.domain:
        create_dns_delegation: false
        database_path: C:\Windows\NTDS
        dns_domain_name: "{{ domain_name }}"
        domain_mode: Win2025
        domain_netbios_name: "{{ netbios }}"
        forest_mode: Win2025
        safe_mode_password: "{{ recovery_password }}"
        sysvol_path: C:\Windows\SYSVOL
        reboot: true
      register: domain_install

    - name: Create NATS server record
      ansible.windows.win_dns_record:
        name: "{{ nats_hostname }}"
        type: "A"
        value: "{{ nats_ip }}"
        zone: "{{ domain_name }}"

    - name: Create PGSQL server record
      ansible.windows.win_dns_record:
        name: "{{ postgres_hostname }}"
        type: "A"
        value: "{{ postgres_ip }}"
        zone: "{{ domain_name }}"

 