---
- name: Domain Controller Setup - PART 1 (Feature Install and Reboot)
  hosts: dc
  vars:
    dc_password: "{{ dc_password }}"
  gather_facts: no
  tasks:
    - name: Ensure initial WinRM is reachable
      ansible.windows.win_wait_for:
        port: 5986
        delay: 5
        timeout: 300
        host: "{{ ansible_host }}"
      
    - name: Set Administrator password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ dc_password }}"
        state: present
      register: admin_pw_result
      retries: 3
      delay: 10
      until: admin_pw_result is succeeded
    
    - name: Ensure required Windows features (AD DS) are installed
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present
      register: feature_result
      # Remove async/poll - let it run synchronously with retries instead
      retries: 2
      delay: 30
      until: feature_result is succeeded
      
    - name: Display feature installation result
      ansible.builtin.debug:
        msg: "Feature installation completed. Reboot required: {{ feature_result.reboot_required | default(false) }}"
      
    - name: Reboot if required by feature installation
      ansible.windows.win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 60
        test_command: 'whoami'
      when: feature_result.reboot_required | default(false)
      register: reboot_result
      
    - name: Wait for system to fully stabilize after reboot
      ansible.windows.win_wait_for:
        port: 5986
        delay: 10
        timeout: 300
        host: "{{ ansible_host }}"
      when: feature_result.reboot_required | default(false)
      
    - name: Verify AD DS feature is installed
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
      register: verify_feature
      failed_when: verify_feature.changed
      
    - name: Completion message
      ansible.builtin.debug:
        msg: "Part 1 completed successfully. AD-DS features are installed. Ready for domain promotion."
