---
# postgresql_install.yml - Updated for RHEL 9 Native + Veeam KB4728 & KB4638
- name: Install and Configure PostgreSQL 15 + PgBouncer for Veeam VB365
  hosts: postgresql
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Check if data disk exists
      ansible.builtin.stat:
        path: "{{ pgsql_data_disk }}"
      register: data_disk
      when: pgsql_data_disk is defined

    - name: Create filesystem on data disk
      ansible.builtin.filesystem:
        fstype: xfs
        dev: "{{ pgsql_data_disk }}"
        opts: -n ftype=1
      when: 
        - pgsql_data_disk is defined
        - data_disk.stat.exists

    - name: Get UUID of the newly formatted disk
      ansible.builtin.command: "blkid -s UUID -o value {{ pgsql_data_disk }}"
      register: disk_uuid_result
      changed_when: false
      when: 
        - pgsql_data_disk is defined
        - data_disk.stat.exists
        
    - name: Create PostgreSQL mount point
      ansible.builtin.file:
        path: "{{ pgsql_mount_point }}"
        state: directory
        mode: '0755'
      when: pgsql_data_disk is defined

    - name: Mount data disk using UUID
      ansible.posix.mount:
        path: "{{ pgsql_mount_point }}"
        src: "UUID={{ disk_uuid_result.stdout }}" 
        fstype: xfs
        opts: defaults,noatime
        state: mounted
      when: 
        - pgsql_data_disk is defined
        - data_disk.stat.exists
        - disk_uuid_result is defined

    # --- PostgreSQL installation (RHEL Native Method) ---
    - name: Enable PostgreSQL 15 module
      ansible.builtin.shell: dnf -y module enable postgresql:15
      register: module_enable
      changed_when: "'Complete!' in module_enable.stdout"

    - name: Install PostgreSQL and dependencies
      ansible.builtin.dnf:
        name:
          - postgresql-server
          - postgresql-contrib
          - pgbouncer
          - python3-psycopg2
        state: present

    - name: Set correct ownership on mount point
      ansible.builtin.file:
        path: "{{ pgsql_mount_point }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
      when: pgsql_data_disk is defined

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{ pgsql_mount_point }}/data/PG_VERSION"
      register: pgdata

    - name: Initialize PostgreSQL with data checksums
      ansible.builtin.command: "postgresql-setup --initdb"
      when: not pgdata.stat.exists
      environment:
        PGSETUP_INITDB_OPTIONS: "--data-checksums"

    # --- PostgreSQL Configuration (Veeam KB4728 requirements) ---
    - name: Configure PostgreSQL - listen_addresses
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"

    - name: Configure PostgreSQL - port
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?port"
        line: "port = {{ postgresql_port }}"

    - name: Configure PostgreSQL - max_connections
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?max_connections"
        line: "max_connections = {{ (pgbouncer_max_user_connections * 1.10) | int }}"

    - name: Configure PostgreSQL - shared_buffers
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?shared_buffers"
        line: "shared_buffers = 4GB"

    - name: Configure PostgreSQL - effective_cache_size
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?effective_cache_size"
        line: "effective_cache_size = 12GB"

    - name: Configure PostgreSQL - maintenance_work_mem
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?maintenance_work_mem"
        line: "maintenance_work_mem = 1GB"

    - name: Configure PostgreSQL - work_mem
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?work_mem"
        line: "work_mem = 16MB"

    - name: Configure PostgreSQL - wal_buffers
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?wal_buffers"
        line: "wal_buffers = 16MB"

    - name: Configure PostgreSQL - checkpoint_completion_target
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?checkpoint_completion_target"
        line: "checkpoint_completion_target = 0.9"

    - name: Configure PostgreSQL - random_page_cost
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?random_page_cost"
        line: "random_page_cost = 1.1"

    - name: Configure PostgreSQL - effective_io_concurrency
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?effective_io_concurrency"
        line: "effective_io_concurrency = 200"

    - name: Configure pg_hba.conf for local connections
      ansible.builtin.blockinfile:
        path: "{{ pgsql_mount_point }}/data/pg_hba.conf"
        block: |
          local   all             all                                     scram-sha-256
          host    all             all             127.0.0.1/32            scram-sha-256
          host    all             all             ::1/128                 scram-sha-256
          host    all             postgres        127.0.0.1/32            scram-sha-256
          host    all             postgres        ::1/128                 scram-sha-256
        marker: "# {mark} LOCAL PGBOUNCER ACCESS"
        insertbefore: "^# TYPE"

    - name: Configure pg_hba.conf for remote Veeam access
      ansible.builtin.blockinfile:
        path: "{{ pgsql_mount_point }}/data/pg_hba.conf"
        block: |
          {% for network in allowed_networks %}
          host    all    all    {{ network }}    scram-sha-256
          {% endfor %}
        marker: "# {mark} VEEAM VB365 REMOTE"

    - name: Start and enable PostgreSQL
      ansible.builtin.systemd:
        name: "postgresql"
        state: started
        enabled: yes

    - name: Wait for PostgreSQL to be ready
      ansible.builtin.wait_for:
        port: "{{ postgresql_port }}"
        delay: 5
        timeout: 60

    - name: Set postgres superuser password
      ansible.builtin.shell: |
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_superuser_password }}';"
      no_log: true

    - name: Create dedicated PgBouncer user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE USER {{ pgbouncer_db_user }} WITH LOGIN PASSWORD '{{ pgbouncer_db_password }}';"
      ignore_errors: yes
      no_log: true

    - name: Create user_search function for PgBouncer
      ansible.builtin.shell: |
        sudo -u postgres psql -d postgres -c "
        CREATE OR REPLACE FUNCTION user_search(uname TEXT)
        RETURNS TABLE (usename name, passwd text) AS
        \$\$
          SELECT usename, passwd FROM pg_shadow WHERE usename = \$1;
        \$\$
        LANGUAGE sql SECURITY DEFINER;"
      register: user_search_result
      changed_when: "'CREATE FUNCTION' in user_search_result.stdout"

    - name: Grant execute on user_search
      ansible.builtin.shell: |
        sudo -u postgres psql -d postgres -c "GRANT EXECUTE ON FUNCTION user_search(text) TO {{ pgbouncer_db_user }};"

    - name: Create Veeam admin user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE USER {{ veeam_db_user }} WITH PASSWORD '{{ veeam_db_password }}';"
      no_log: true
      ignore_errors: yes

    - name: Grant superuser privileges to Veeam user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "ALTER USER {{ veeam_db_user }} WITH SUPERUSER CREATEROLE CREATEDB;"

    - name: Create PgBouncer configuration directory
      ansible.builtin.file:
        path: /etc/pgbouncer
        state: directory
        owner: pgbouncer
        group: pgbouncer
        mode: '0750'

    - name: Create PgBouncer userlist.txt
      ansible.builtin.copy:
        dest: /etc/pgbouncer/userlist.txt
        mode: '0600'
        owner: pgbouncer
        group: pgbouncer
        content: |
          "{{ pgbouncer_db_user }}" "{{ pgbouncer_db_password }}"
          "{{ veeam_db_user }}" "{{ veeam_db_password }}"
      no_log: true

    - name: Configure PgBouncer ini file
      ansible.builtin.copy:
        dest: /etc/pgbouncer/pgbouncer.ini
        owner: pgbouncer
        group: pgbouncer
        mode: '0640'
        content: |
          [databases]
          postgres = host=127.0.0.1 port={{ postgresql_port }} dbname=postgres
          VeeamBackup365 = host=127.0.0.1 port={{ postgresql_port }} dbname=VeeamBackup365
          veeambackup365 = host=127.0.0.1 port={{ postgresql_port }} dbname=veeambackup365

          [pgbouncer]
          logfile = /var/log/pgbouncer/pgbouncer.log
          pidfile = /run/pgbouncer/pgbouncer.pid
          listen_addr = *
          listen_port = 6432
          unix_socket_dir = /tmp
          auth_type = scram-sha-256
          auth_file = /etc/pgbouncer/userlist.txt
          auth_query = SELECT usename, passwd FROM user_search($1)
          auth_user = {{ pgbouncer_db_user }}
          auth_dbname = postgres
          pool_mode = transaction
          max_client_conn = {{ pgbouncer_max_client_conn }}
          default_pool_size = {{ pgbouncer_default_pool_size }}
          max_user_connections = {{ pgbouncer_max_user_connections }}
          server_reset_query = DISCARD ALL
          ignore_startup_parameters = extra_float_digits

    - name: Enable and start PgBouncer
      ansible.builtin.systemd:
        name: pgbouncer
        enabled: yes
        state: restarted

    - name: Open firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - "{{ postgresql_port }}/tcp"
        - "6432/tcp"

    # --- STATUS CHECKS (Din originale summary logik) ---
    - name: Get PostgreSQL status
      ansible.builtin.command: systemctl status postgresql
      register: pg_status
      changed_when: false
      ignore_errors: yes

    - name: Get PgBouncer status
      ansible.builtin.command: systemctl status pgbouncer
      register: pgbouncer_status
      changed_when: false
      ignore_errors: yes

    - name: Get disk usage
      ansible.builtin.command: df -h {{ pgsql_mount_point }}
      register: disk_usage
      changed_when: false
      when: pgsql_data_disk is defined

    - name: Test PgBouncer connection with Veeam user
      ansible.builtin.shell: |
        PGPASSWORD='{{ veeam_db_password }}' psql -h 127.0.0.1 -p 6432 -U {{ veeam_db_user }} -d postgres -c "SELECT version();"
      register: pgbouncer_test
      changed_when: false
      ignore_errors: yes
      no_log: true

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================================="
          - "PostgreSQL 15 + PgBouncer Installation Complete (RHEL Native)"
          - "======================================================================="
          - "PostgreSQL Configuration:"
          - "  - Port: {{ postgresql_port }}"
          - "  - Admin User: {{ veeam_db_user }}"
          - "  - Status: {{ 'Running' if 'active (running)' in pg_status.stdout else 'Check Manually' }}"
          - "-----------------------------------------------------------------------"
          - "PgBouncer Configuration:"
          - "  - Port: 6432"
          - "  - Status: {{ 'Running' if 'active (running)' in pgbouncer_status.stdout else 'Check Manually' }}"
          - "  - Connection Test: {{ 'SUCCESS' if pgbouncer_test.rc == 0 else 'FAILED' }}"
          - "-----------------------------------------------------------------------"
          - "Disk Usage:"
          - "{{ disk_usage.stdout_lines | default(['N/A']) }}"
          - "======================================================================="