---
- name: Install and Configure PostgreSQL 15 + PgBouncer for Veeam VB365
  hosts: postgresql
  become: yes
  gather_facts: yes

  handlers:
    - name: restart postgresql
      ansible.builtin.systemd:
        name: postgresql-16
        state: restarted
        daemon_reload: yes

    - name: restart pgbouncer
      ansible.builtin.systemd:
        name: pgbouncer
        state: restarted

  tasks:



    - name: Update all system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: system_update

    - name: Reboot if kernel was updated
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: system_update.changed

    # --- Disk og mount ---
    - name: Check if data disk exists
      ansible.builtin.stat:
        path: "{{ pgsql_data_disk }}"
      register: data_disk
      when: pgsql_data_disk is defined

    - name: Create filesystem on data disk
      ansible.builtin.filesystem:
        fstype: xfs
        dev: "{{ pgsql_data_disk }}"
        opts: -n ftype=1
      when:
        - pgsql_data_disk is defined
        - data_disk.stat.exists

    - name: Get UUID of the newly formatted disk
      ansible.builtin.command: "blkid -s UUID -o value {{ pgsql_data_disk }}"
      register: disk_uuid_result
      changed_when: false
      when:
        - pgsql_data_disk is defined
        - data_disk.stat.exists

    - name: Create PostgreSQL mount point
      ansible.builtin.file:
        path: "{{ pgsql_mount_point }}"
        state: directory
        mode: '0755'
      when: pgsql_data_disk is defined

    - name: Mount data disk using UUID
      ansible.posix.mount:
        path: "{{ pgsql_mount_point }}"
        src: "UUID={{ disk_uuid_result.stdout }}"
        fstype: xfs
        opts: defaults,noatime
        state: mounted
      when:
        - pgsql_data_disk is defined
        - data_disk.stat.exists
        - disk_uuid_result is defined

    # --- Installation ---
    - name: Install PostgreSQL 16 repository
      ansible.builtin.dnf:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Disable built-in PostgreSQL module
      ansible.builtin.shell: dnf -y module disable postgresql
      register: module_disable
      changed_when: "'Complete!' in module_disable.stdout"

    - name: Install PostgreSQL 16 and dependencies
      ansible.builtin.dnf:
        name:
          - postgresql16-server
          - postgresql16-contrib
          - pgbouncer
          - python3-psycopg2
        state: present

    - name: Set correct ownership on mount point
      ansible.builtin.file:
        path: "{{ pgsql_mount_point }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
      when: pgsql_data_disk is defined

    - name: Create systemd override directory for PostgreSQL
      ansible.builtin.file:
        path: /etc/systemd/system/postgresql-16.service.d
        state: directory
        mode: '0755'

    - name: Set PGDATA i systemd override
      ansible.builtin.copy:
        dest: /etc/systemd/system/postgresql-16.service.d/override.conf
        content: |
          [Service]
          Environment=PGDATA={{ pgsql_mount_point }}/data
      notify: restart postgresql

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    # --- Init og start ---
    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{ pgsql_mount_point }}/data/PG_VERSION"
      register: pgdata

    - name: Initialize PostgreSQL with data checksums
      ansible.builtin.command: /usr/pgsql-16/bin/postgresql-16-setup initdb
      when: not pgdata.stat.exists
      environment:
        PGSETUP_INITDB_OPTIONS: "--data-checksums"
        PGDATA: "{{ pgsql_mount_point }}/data"

    - name: Start and enable PostgreSQL
      ansible.builtin.systemd:
        name: postgresql-16
        state: started
        enabled: yes
        daemon_reload: yes

    # --- PostgreSQL konfiguration ---
    - name: Configure PostgreSQL - listen_addresses
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"
      notify: restart postgresql

    - name: Configure PostgreSQL - port
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?port"
        line: "port = {{ postgresql_port }}"
      notify: restart postgresql

    - name: Configure PostgreSQL - max_connections
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?max_connections"
        line: "max_connections = {{ (pgbouncer_max_user_connections * 1.10) | int }}"
      notify: restart postgresql

    - name: Configure PostgreSQL - shared_buffers
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?shared_buffers"
        line: "shared_buffers = 4GB"
      notify: restart postgresql

    - name: Configure PostgreSQL - effective_cache_size
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?effective_cache_size"
        line: "effective_cache_size = 12GB"
      notify: restart postgresql

    - name: Configure PostgreSQL - maintenance_work_mem
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?maintenance_work_mem"
        line: "maintenance_work_mem = 1GB"
      notify: restart postgresql

    - name: Configure PostgreSQL - work_mem
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?work_mem"
        line: "work_mem = 16MB"
      notify: restart postgresql

    - name: Configure PostgreSQL - wal_buffers
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?wal_buffers"
        line: "wal_buffers = 16MB"
      notify: restart postgresql

    - name: Configure PostgreSQL - checkpoint_completion_target
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?checkpoint_completion_target"
        line: "checkpoint_completion_target = 0.9"
      notify: restart postgresql

    - name: Configure PostgreSQL - random_page_cost
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?random_page_cost"
        line: "random_page_cost = 1.1"
      notify: restart postgresql

    - name: Configure PostgreSQL - effective_io_concurrency
      ansible.builtin.lineinfile:
        path: "{{ pgsql_mount_point }}/data/postgresql.conf"
        regexp: "^#?effective_io_concurrency"
        line: "effective_io_concurrency = 200"
      notify: restart postgresql

    - name: Configure pg_hba.conf
      ansible.builtin.copy:
        dest: "{{ pgsql_mount_point }}/data/pg_hba.conf"
        owner: postgres
        group: postgres
        mode: '0600'
        content: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD

          host    all    {{ veeam_db_user }}    0.0.0.0/0    scram-sha-256
          host    all    {{ veeam_db_user }}    ::/0         scram-sha-256
          host    all    all                    0.0.0.0/0    md5
          local   all    postgres               trust
          {% for extra_user in pgbouncer_extra_users | default([]) %}
          host    all    {{ extra_user }}        0.0.0.0/0    md5
          {% endfor %}

          ###### PGBouncer additional config
          local    all    all              scram-sha-256
          host     all    all    127.0.0.1/32    scram-sha-256
          host     all    all    ::1/128         scram-sha-256
      notify: restart postgresql

    - name: Wait for PostgreSQL to be ready
      ansible.builtin.wait_for:
        port: "{{ postgresql_port }}"
        delay: 5
        timeout: 60

    # --- Brugere og database ---
    - name: Set postgres superuser password
      ansible.builtin.shell: |
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_superuser_password }}';"
      no_log: true

    - name: Check if PgBouncer user exists
      ansible.builtin.shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ pgbouncer_db_user }}'"
      register: pgbouncer_user_exists
      changed_when: false

    - name: Create dedicated PgBouncer user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE USER {{ pgbouncer_db_user }} WITH LOGIN PASSWORD '{{ pgbouncer_db_password }}';"
      when: pgbouncer_user_exists.stdout != "1"
      no_log: true

    - name: Create user_search function for PgBouncer
      ansible.builtin.shell: |
        sudo -u postgres psql -d postgres -c "
        CREATE OR REPLACE FUNCTION user_search(uname TEXT)
        RETURNS TABLE (usename name, passwd text) AS
        \$\$
          SELECT usename, passwd FROM pg_shadow WHERE usename = \$1;
        \$\$
        LANGUAGE sql SECURITY DEFINER;"
      register: user_search_result
      changed_when: "'CREATE FUNCTION' in user_search_result.stdout"

    - name: Grant execute on user_search
      ansible.builtin.shell: |
        sudo -u postgres psql -d postgres -c "GRANT EXECUTE ON FUNCTION user_search(text) TO {{ pgbouncer_db_user }};"

    - name: Check if Veeam user exists
      ansible.builtin.shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ veeam_db_user }}'"
      register: veeam_user_exists
      changed_when: false

    - name: Create Veeam admin user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE USER {{ veeam_db_user }} WITH PASSWORD '{{ veeam_db_password }}';"
      when: veeam_user_exists.stdout != "1"
      no_log: true

    - name: Grant superuser privileges to Veeam user
      ansible.builtin.shell: |
        sudo -u postgres psql -c "ALTER USER {{ veeam_db_user }} WITH SUPERUSER CREATEROLE CREATEDB;"

    - name: Create VeeamBackup365 database
      ansible.builtin.shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='VeeamBackup365'"
      register: veeam_db_exists
      changed_when: false

    - name: Create VeeamBackup365 database
      ansible.builtin.shell: |
        sudo -u postgres psql -c "CREATE DATABASE \"VeeamBackup365\" OWNER {{ veeam_db_user }};"
      when: veeam_db_exists.stdout != "1"

    # --- PgBouncer ---
    - name: Create PgBouncer configuration directory
      ansible.builtin.file:
        path: /etc/pgbouncer
        state: directory
        owner: pgbouncer
        group: pgbouncer
        mode: '0750'

    - name: Create PgBouncer userlist.txt
      ansible.builtin.copy:
        dest: /etc/pgbouncer/userlist.txt
        mode: '0600'
        owner: pgbouncer
        group: pgbouncer
        content: |
          "{{ pgbouncer_db_user }}" "{{ pgbouncer_db_password }}"
          "{{ veeam_db_user }}" "{{ veeam_db_password }}"
      no_log: true
      notify: restart pgbouncer

    - name: Configure PgBouncer ini file
      ansible.builtin.copy:
        dest: /etc/pgbouncer/pgbouncer.ini
        owner: pgbouncer
        group: pgbouncer
        mode: '0640'
        content: |
          [databases]
          * = host=/var/run/postgresql auth_user={{ pgbouncer_db_user }}
          VeeamBackup365 = host=/var/run/postgresql auth_user={{ pgbouncer_db_user }} dbname=VeeamBackup365 pool_size=200

          [pgbouncer]
          logfile = /var/log/pgbouncer/pgbouncer.log
          pidfile = /var/run/pgbouncer/pgbouncer.pid
          listen_addr = *
          listen_port = 6432
          unix_socket_dir = /var/run/pgbouncer
          unix_socket_mode = 0755
          unix_socket_group = postgres
          auth_type = hba
          auth_file = /etc/pgbouncer/userlist.txt
          auth_hba_file = /etc/pgbouncer/pgbouncer_hba.conf
          auth_query = SELECT usename, passwd FROM user_search($1)
          auth_dbname = postgres
          admin_users = {{ pgbouncer_db_user }}, postgres, root
          stats_users = {{ pgbouncer_db_user }}, postgres, root
          pool_mode = transaction
          ignore_startup_parameters = extra_float_digits,application_name
          max_client_conn = {{ pgbouncer_max_client_conn }}
          max_user_connections = {{ pgbouncer_max_user_connections }}
          default_pool_size = {{ pgbouncer_default_pool_size }}
          log_connections = 0
          log_disconnections = 0
          stats_period = 180
          server_idle_timeout = 60
          server_connect_timeout = 120
          query_wait_timeout = 55
          tcp_defer_accept = 45
      notify: restart pgbouncer


    - name: Create pgbouncer_hba.conf
      ansible.builtin.copy:
        dest: /etc/pgbouncer/pgbouncer_hba.conf
        owner: pgbouncer
        group: pgbouncer
        mode: '0640'
        content: |
          host    all    {{ veeam_db_user }}    0.0.0.0/0    scram-sha-256
          host    all    {{ veeam_db_user }}    ::/0         scram-sha-256
          host    all    all                    0.0.0.0/0    md5
          local   all    postgres               trust
          {% for extra_user in pgbouncer_extra_users | default([]) %}
          host    all    {{ extra_user }}        0.0.0.0/0    md5
          {% endfor %}

          ###### PGBouncer additional config
          local    all    all              scram-sha-256
          host     all    all    127.0.0.1/32    scram-sha-256
          host     all    all    ::1/128         scram-sha-256
      notify: restart pgbouncer


    - name: Enable and start PgBouncer
      ansible.builtin.systemd:
        name: pgbouncer
        enabled: yes
        state: started

    - name: Open firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - "{{ postgresql_port }}/tcp"
        - "6432/tcp"

    # --- Status checks ---
    - name: Get PostgreSQL status
      ansible.builtin.command: systemctl status postgresql-16
      register: pg_status
      changed_when: false
      ignore_errors: yes

    - name: Get PgBouncer status
      ansible.builtin.command: systemctl status pgbouncer
      register: pgbouncer_status
      changed_when: false
      ignore_errors: yes

    - name: Get disk usage
      ansible.builtin.command: df -h {{ pgsql_mount_point }}
      register: disk_usage
      changed_when: false
      when: pgsql_data_disk is defined

    - name: Test PgBouncer connection with Veeam user
      ansible.builtin.shell: |
        PGPASSWORD='{{ veeam_db_password }}' psql -h 127.0.0.1 -p 6432 -U {{ veeam_db_user }} -d postgres -c "SELECT version();"
      register: pgbouncer_test
      changed_when: false
      ignore_errors: yes
      no_log: true

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================================="
          - "PostgreSQL 15 + PgBouncer Installation Complete (RHEL Native)"
          - "======================================================================="
          - "PostgreSQL Configuration:"
          - "  - Port: {{ postgresql_port }}"
          - "  - Admin User: {{ veeam_db_user }}"
          - "  - Status: {{ 'Running' if 'active (running)' in pg_status.stdout else 'Check Manually' }}"
          - "-----------------------------------------------------------------------"
          - "PgBouncer Configuration:"
          - "  - Port: 6432"
          - "  - Status: {{ 'Running' if 'active (running)' in pgbouncer_status.stdout else 'Check Manually' }}"
          - "  - Connection Test: {{ 'SUCCESS' if pgbouncer_test.rc == 0 else 'FAILED' }}"
          - "-----------------------------------------------------------------------"
          - "Disk Usage:"
          - "{{ disk_usage.stdout_lines | default(['N/A']) }}"
          - "======================================================================="