- name: VB365 Download
  hosts: all 

  tasks:
  
  
    - name: Create C:\temp folder
      win_file:
      path: C:\temp
      state: directory

    - name: Download the VB365 installer
      ansible.windows.win_get_url:
        url: 'https://download2.veeam.com/VBO/v6/VeeamBackupMicrosoft365_6.1.0.438_P20221215.iso'
        dest: 'C:\temp\VeeamBackupMicrosoft365_6.1.0.438_P20221215.iso'

    - name: Ensure an ISO is mounted
      community.windows.win_disk_image:
        image_path: C:\temp\VeeamBackupMicrosoft365_6.1.0.438_P20221215.iso
        state: present
      register: disk_image_out

    - name: Run installer from mounted ISO
      ansible.windows.win_package:
        path: '{{ disk_image_out.mount_paths[0] }}Backup\Veeam.Backup365.msi'
        arguments: '/qn ADDLOCAL=BR_OFFICE365,CONSOLE_OFFICE365,PS_OFFICE365,REST_OFFICE365 ACCEPT_THIRDPARTY_LICENSES=1 ACCEPT_EULA=1'
        state: present

    - name: Unmount ISO
      community.windows.win_disk_image:
        image_path: C:\temp\VeeamBackupMicrosoft365_6.1.0.438_P20221215.iso
        state: absent

    - name: UserPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: MaxUserPort
        data: 65000
        type: dword
 
    - name: TCPPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: TcpTimedWaitDelay
        data: 30
        type: dword
        
        
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: yes
        
    
    - name: Allow TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
