- name: Proxy deployment
  hosts: all
  tasks:
    - name: UserPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: MaxUserPort
        data: 65000
        type: dword
 
    - name: TCPPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: TcpTimedWaitDelay
        data: 30
        type: dword
        
    - name: Set multiple lookup addresses on all visible adapters
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
          - 10.1.0.4
        log_path: C:\dns_log.txt

    - name: Join Domain
      win_domain_membership:
        dns_domain_name: vpc.apac.local
        domain_admin_user: administrator@vpc.apac.local
        domain_admin_password: JGnh3tnmFCETFVz74VkC
        state: domain
      register: domain_state
      
    - debug: var=domain_state
    
    - name: Allow TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
        
    - name: Set timezone to 'GMT Standard Time' (GMT)
      win_timezone:
        timezone: GMT Standard Time
        
    - name: Reboot the machine with all defaults
      ansible.windows.win_reboot:

