- name: VB365 v8.2 Download and Installation
  hosts: all
  vars:
    vb365_version: "8.2.0.2202"
    vb365_iso_url: "https://download2.veeam.com/VBO/v8/VeeamBackupMicrosoft365_8.2.0.2202.iso"
    vb365_iso_filename: "VeeamBackupMicrosoft365_8.2.0.2202.iso"
    vb365_iso_path: "C:\\{{ vb365_iso_filename }}"
    
    # Disse variabler forventes fra Terraform-genereret fil
    # postgres_host: "{{ postgres_host }}"
    # postgres_port: "{{ postgres_port | default(5432) }}"
    # postgres_database: "{{ postgres_database }}"
    # postgres_user: "{{ postgres_user }}"
    # postgres_password: "{{ postgres_password }}"
    # nats_host: "{{ nats_host }}"
    # nats_port: "{{ nats_port | default(4222) }}"
  collections:
    - community.windows
    - ansible.windows
    - microsoft.ad
  tasks:
    - name: Set timezone to GMT Standard Time
      ansible.windows.win_timezone:
        timezone: GMT Standard Time



    - name: Configure MaxUserPort registry setting
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: MaxUserPort
        data: 65000
        type: dword

    - name: Configure TcpTimedWaitDelay registry setting
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: TcpTimedWaitDelay
        data: 30
        type: dword

 
    - name: Configure DNS client settings (PowerShell alternative)
      ansible.windows.win_shell: |
            # Find the adapter that is currently connected (e.g., has an IP address)
            $adapter = Get-NetAdapter | Where-Object { $_.Status -eq "Up" -and $_.LinkSpeed -ne "" } | Select-Object -First 1
            
            # Hvis adapteren findes, sæt DNS-serverne
            if ($adapter) {
                Set-DnsClientServerAddress -InterfaceAlias $adapter.Name -ServerAddresses ("{{ network_address }}.201", "{{ network_address }}.202")
                Write-Host "Successfully set DNS for adapter $($adapter.Name)"
            } else {
                Write-Host "No active network adapter found to set DNS."
            }

    - name: Join domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain }}"
        domain_admin_user: "{{ domain_user }}@{{ domain }}"
        domain_admin_password: "{{ domain_user_password }}"
        #domain_server: "{{ domain_controller }}"
        state: domain
      register: domain_state

    - name: Display domain join result
      ansible.builtin.debug:
        var: domain_state

    - name: Configure firewall - Remote Desktop (3389)
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Configure firewall - Controller Communication (9193)
      community.windows.win_firewall_rule:
        name: Controller Communication 9193
        localport: 9193
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Configure firewall - SMB (445)
      community.windows.win_firewall_rule:
        name: Controller Communication 445
        localport: 445
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Configure firewall - Controller Communication (9194)
      community.windows.win_firewall_rule:
        name: Controller Communication 9194
        localport: 9194
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Configure firewall - HTTPS (4443)
      community.windows.win_firewall_rule:
        name: Controller Communication 4443
        localport: 4443
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes

    - name: Configure firewall - PostgreSQL (5432)
      community.windows.win_firewall_rule:
        name: PostgreSQL
        localport: 5432
        action: allow
        direction: out
        protocol: tcp
        state: present
        enabled: yes
      when: postgres_host is defined

    - name: Configure firewall - NATS (4222)
      community.windows.win_firewall_rule:
        name: NATS
        localport: 4222
        action: allow
        direction: out
        protocol: tcp
        state: present
        enabled: yes
      when: nats_host is defined


    - name: Download VB365 v8.2 installer
      ansible.windows.win_get_url:
        url: "{{ vb365_iso_url }}"
        dest: "{{ vb365_iso_path }}"
        timeout: 3600
      register: download_result

    - name: Mount VB365 ISO
      community.windows.win_disk_image:
        image_path: "{{ vb365_iso_path }}"
        state: present
      register: disk_image_out

    - name: Display mount path for debugging
      ansible.builtin.debug:
        var: disk_image_out.mount_paths[0]
    - name: Tjek PostgreSQL forbindelse
      ansible.windows.win_shell: |
        Test-NetConnection -ComputerName {{ postgresql.postgres_host }} -Port {{ postgresql.postgres_port | default(6432) }}
      register: pg_check

    - name: Tjek NATS forbindelse  
      ansible.windows.win_shell: |
        Test-NetConnection -ComputerName {{ nats.host }} -Port {{ nats.port | default(4222) }}
      register: nats_check

    - name: Install VB365 v8.2 with external PostgreSQL and NATS
      ansible.windows.win_package:
        path: "{{ disk_image_out.mount_paths[0] }}Backup\\Veeam.Backup365.msi"
        arguments: >-
          /L*V C:\\veeam_install_log.log /qn ADDLOCAL=BR_OFFICE365,CONSOLE_OFFICE365,PS_OFFICE365,REST_OFFICE365 ACCEPT_THIRDPARTY_LICENSES=1 ACCEPT_EULA=1 CONNECTION="Host={{ postgresql.postgres_host }};Port={{ postgresql.postgres_port | default(6432) }};Database={{ postgresql.postgres_database }};Username={{ postgresql.postgres_user }};Password={{ postgresql.postgres_password }}" JETSTREAM_CONNECTION="nats://{{ nats.username }}:{{ nats.password }}@{{ nats.host }}:{{ nats.port | default(4222) }}"
        state: present
        product_id: "{3F8E3E4D-7E3E-4F3E-8E3E-4F3E8E3E4F3E}"
      register: install_result
      
    - name: Hent Veeam install log ved fejl
      ansible.windows.win_shell: Get-Content C:\veeam_install_log.log | Select-String "error|fail|Return value 3" -CaseSensitive:$false
      when: install_result is failed
      ignore_errors: true

    - name: Display installation result
      ansible.builtin.debug:
        var: install_result

    - name: Unmount ISO
      community.windows.win_disk_image:
        image_path: "{{ vb365_iso_path }}"
        state: absent


    - name: Reboot server after installation
      ansible.windows.win_reboot:
        reboot_timeout: 600
#Kør kommando til at sætte restore drev op
#Kør kommando til at sætte veeam til at bruge restor drev

#         # PostgreSQL connection details
# postgres_host: "postgres-server.vb365.2any.cloud"
# postgres_port: 5432
# postgres_database: "VeeamBackup365"
# postgres_user: "veeam_admin"
# postgres_password: "{{ vault_postgres_password }}"  # Brug Ansible Vault!

# # NATS connection details
# nats_host: "nats-server.vb365.2any.cloud"
# nats_port: 4222

# # Domain information (hvis de skal variere per miljø)
# domain_name: "VB365.2any.cloud"
# domain_admin_user: "ADSA@VB365.2any.cloud"
# domain_admin_password: "{{ vault_domain_password }}"  # Brug Ansible Vault!

# # DNS servers
# dns_servers:
#   - 10.251.132.7
#   - 10.251.132.6