- name: VB365 Download
  hosts: all 

  tasks:
    - name: UserPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: MaxUserPort
        data: 65000
        type: dword
 
    - name: TCPPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: TcpTimedWaitDelay
        data: 30
        type: dword
        
    - name: Set multiple lookup addresses on all visible adapters (usually physical adapters that are in the Up state), with debug logging to a file
      win_dns_client:
       adapter_names: '*'
       ipv4_addresses:
       - 10.1.0.4
       log_path: C:\dns_log.txt

        
    
    - name: Allow TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
        
    - name: Set timezone to 'GMT Standard Time' (GMT)
      win_timezone:
        timezone: GMT Standard Time 
    - hosts: winclient
      gather_facts: no
      tasks:
      - ansible.windows.win_domain_membership:
          dns_domain_name: vpc.apac.local
          domain_admin_user: administrator
          domain_admin_password: JGnh3tnmFCETFVz74VkC
          domain_ou_path: ""
          state: domain
        register: domain_state

      - ansible.windows.win_reboot:
        when: domain_state.reboot_required
        
     - name: "Join Domain"
       win_domain_membership:
         dns_domain_name: vpc.apac.local
         domain_admin_user: administrator
         domain_admin_password: JGnh3tnmFCETFVz74VkC
            state: domain
         register: domain_state
      - debug: var=domain_state
      - win_reboot:
          when: domain_state.reboot_required
