- name: Proxy deployment
  hosts: all
  tasks:
    - name: UserPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: MaxUserPort
        data: 65000
        type: dword
 
    - name: TCPPort
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: TcpTimedWaitDelay
        data: 30
        type: dword
        
    - name: Set timezone to 'GMT Standard Time' (GMT)
      win_timezone:
        timezone: GMT Standard Time

    - name: Set Windows Keyboard Layout to Danish (Denmark)
      ansible.builtin.win_shell: |
        $locale = "da-DK"
        $keyboard = "00000406"
        
        $controlPanel = New-Object -ComObject "Shell.Application"
        $controlPanel.NameSpace('::{26EE0668-A00A-44D7-9371-BEB064C98683}\0\::{7B81BE6A-CE2B-4676-A29E-EB907A5126C5}').ParseName("Region and Language").InvokeVerb("open")
    
        Start-Sleep -Seconds 3  # Wait for the control panel to open
    
        $keyboardTab = Get-Process | Where-Object {$_.MainWindowTitle -eq "Region"} | ForEach-Object {$_.MainWindowHandle}
        Set-WinUILanguageOverride -Language $locale
        SendKeys "{TAB}"
        Start-Sleep -Milliseconds 500
        [System.Windows.Forms.SendKeys]::SendWait("$keyboard%")
        Start-Sleep -Milliseconds 500
        [System.Windows.Forms.SendKeys]::SendWait("~")
        Start-Sleep -Milliseconds 500
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
    
      become: yes
      become_method: runas
      become_user: Administrator

        
    - name: Set multiple lookup addresses on all visible adapters
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
          - 10.251.132.7
          - 10.251.132.6
        log_path: C:\dns_log.txt

    - name: Join Domain
      win_domain_membership:
        dns_domain_name: VB365.2any.cloud
        domain_admin_user: ADSA@VB365.2any.cloud
        domain_admin_password: d!s6*NPtLebfpMgU9KzQoMQ.bEUt4Zrkx
        state: domain
      register: domain_state
      
    - debug: var=domain_state
    
    - name: Allow TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
        
    - name: Allow TCP port 9193
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 9193
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes


        
    - name: Reboot the machine with all defaults
      ansible.windows.win_reboot:

